profile: if HOME is missing report error and quit
HOME is expected to be there. Either HOME is automatically
set to USERPROFILE or it was set present in the environment.
There's no need to create the directory. If it is missing
there's something fundamentally wrong. Hence, we report an
error and quit.

Signed-off-by: Steffen Prohaska <prohaska@zib.de>

diff --git a/etc/profile b/etc/profile
--- a/etc/profile
+++ b/etc/profile
@@ -33,7 +33,11 @@ if [ -z "$HOME" ]; then
 fi
 
 if [ ! -d "$HOME" ]; then
-  mkdir -p "$HOME"
+	echo "Error: HOME directory '$HOME' doen't exist!"
+	echo "Please fix this error and restart shell."
+	echo "Press key to quit."
+	read dummy
+	exit 1
 fi
 
 # normalize HOME to unix path
